name: OpenAPIClient
targets:
  OpenAPIClient:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [OpenAPIClient]
    info:
      path: ./Info.plist
      version: 1.1.6
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
