//
// ApikeyEditObjectV1Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request for PUT /1/object/apikey/{pkiApikeyID} */
public struct ApikeyEditObjectV1Request: Codable, JSONEncodable, Hashable {

    public var objApikey: ApikeyRequestCompound

    public init(objApikey: ApikeyRequestCompound) {
        self.objApikey = objApikey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case objApikey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(objApikey, forKey: .objApikey)
    }
}

