//
// AuthenticateAuthenticateV2Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request for the /2/module/authenticate/authenticate API Request */
public struct AuthenticateAuthenticateV2Request: Codable, Hashable {

    /** The customer code assigned to your account */
    public var pksCustomerCode: String
    /** The email address. */
    public var sEmailAddress: String?
    /** The Login name of the User. */
    public var sUserLoginname: String?
    /** A Password.  Must meet complexity requirements */
    public var sPassword: String

    public init(pksCustomerCode: String, sEmailAddress: String? = nil, sUserLoginname: String? = nil, sPassword: String) {
        self.pksCustomerCode = pksCustomerCode
        self.sEmailAddress = sEmailAddress
        self.sUserLoginname = sUserLoginname
        self.sPassword = sPassword
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pksCustomerCode
        case sEmailAddress
        case sUserLoginname
        case sPassword
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pksCustomerCode, forKey: .pksCustomerCode)
        try container.encodeIfPresent(sEmailAddress, forKey: .sEmailAddress)
        try container.encodeIfPresent(sUserLoginname, forKey: .sUserLoginname)
        try container.encode(sPassword, forKey: .sPassword)
    }
}
