//
// CommunicationGetCountV1ResponseMPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for GET /1/module/communication/getCount */
public struct CommunicationGetCountV1ResponseMPayload: Codable, JSONEncodable, Hashable {

    /** The number of total signatures in the Ezsigntemplate. */
    public var iCommunicationCount: Int

    public init(iCommunicationCount: Int) {
        self.iCommunicationCount = iCommunicationCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case iCommunicationCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(iCommunicationCount, forKey: .iCommunicationCount)
    }
}

