//
// CommonGetAutocompleteDisabledV1ResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CommonGetAutocompleteDisabledV1ResponseAllOf: Codable, JSONEncodable, Hashable {

    /** Generic Autocomplete Response with a bDisabled Flag */
    public var mPayload: [CustomAutocompleteElementDisabledResponse]

    public init(mPayload: [CustomAutocompleteElementDisabledResponse]) {
        self.mPayload = mPayload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mPayload
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mPayload, forKey: .mPayload)
    }
}

