//
// CompanyGetAutocompleteV2ResponseMPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for POST /2/object/company/getAutocomplete */
public struct CompanyGetAutocompleteV2ResponseMPayload: Codable, JSONEncodable, Hashable {

    /** An array of Company autocomplete element response. */
    public var aObjCompany: [CompanyAutocompleteElementResponse]?

    public init(aObjCompany: [CompanyAutocompleteElementResponse]? = nil) {
        self.aObjCompany = aObjCompany
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aObjCompany = "a_objCompany"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(aObjCompany, forKey: .aObjCompany)
    }
}

