//
// CustomWordPositionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A Word Position Object */
public struct CustomWordPositionResponse: Codable, Hashable {

    /** The page where the word occurence was found */
    public var iPage: Int?
    /** The X coordinate (Horizontal) where the Word occurence was found.  Coordinate is calculated at 100dpi (dot per inch). */
    public var iX: Int?
    /** The Y coordinate (Vertical) where the Word occurence was found.  Coordinate is calculated at 100dpi (dot per inch). */
    public var iY: Int?

    public init(iPage: Int? = nil, iX: Int? = nil, iY: Int? = nil) {
        self.iPage = iPage
        self.iX = iX
        self.iY = iY
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case iPage
        case iX
        case iY
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(iPage, forKey: .iPage)
        try container.encodeIfPresent(iX, forKey: .iX)
        try container.encodeIfPresent(iY, forKey: .iY)
    }
}

