//
// EmailstaticResponseCompound.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An Emailstatic Object and children to create a complete structure */
public struct EmailstaticResponseCompound: Codable, JSONEncodable, Hashable {

    /** The unique ID of the Emailstatic */
    public var pkiEmailstaticID: Int
    /** The email address. */
    public var sEmailstaticAddress: String

    public init(pkiEmailstaticID: Int, sEmailstaticAddress: String) {
        self.pkiEmailstaticID = pkiEmailstaticID
        self.sEmailstaticAddress = sEmailstaticAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pkiEmailstaticID
        case sEmailstaticAddress
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pkiEmailstaticID, forKey: .pkiEmailstaticID)
        try container.encode(sEmailstaticAddress, forKey: .sEmailstaticAddress)
    }
}

