//
// EzsigntemplatedocumentEditEzsigntemplateformfieldgroupsV1Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request for PUT /1/object/ezsigntemplatedocument/{pkiEzsigntemplatedocumentID}/editEzsigntemplateformfieldgroups */
public struct EzsigntemplatedocumentEditEzsigntemplateformfieldgroupsV1Request: Codable, JSONEncodable, Hashable {

    public var aObjEzsigntemplateformfieldgroup: [EzsigntemplateformfieldgroupRequestCompound]

    public init(aObjEzsigntemplateformfieldgroup: [EzsigntemplateformfieldgroupRequestCompound]) {
        self.aObjEzsigntemplateformfieldgroup = aObjEzsigntemplateformfieldgroup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aObjEzsigntemplateformfieldgroup = "a_objEzsigntemplateformfieldgroup"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aObjEzsigntemplateformfieldgroup, forKey: .aObjEzsigntemplateformfieldgroup)
    }
}

