//
// EzsigndocumentCreateObjectV1Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request for the /1/object/ezsigndocument/createObject API Request */
public struct EzsigndocumentCreateObjectV1Request: Codable {

    public var objEzsigndocument: EzsigndocumentRequest?
    public var objEzsigndocumentCompound: EzsigndocumentRequestCompound?

    public init(objEzsigndocument: EzsigndocumentRequest? = nil, objEzsigndocumentCompound: EzsigndocumentRequestCompound? = nil) {
        self.objEzsigndocument = objEzsigndocument
        self.objEzsigndocumentCompound = objEzsigndocumentCompound
    }

}
