//
// EzsignsignatureEditObjectV1Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request for PUT /1/object/ezsignsignature/{pkiEzsignsignatureID} */
public struct EzsignsignatureEditObjectV1Request: Codable, JSONEncodable, Hashable {

    public var objEzsignsignature: EzsignsignatureRequestCompound

    public init(objEzsignsignature: EzsignsignatureRequestCompound) {
        self.objEzsignsignature = objEzsignsignature
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case objEzsignsignature
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(objEzsignsignature, forKey: .objEzsignsignature)
    }
}

