//
// EzsignfoldersignerassociationCreateObjectV1Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request for the /1/object/ezsignfoldersignerassociation/createObject API Request */
public struct EzsignfoldersignerassociationCreateObjectV1Request: Codable {

    public var objEzsignfoldersignerassociation: EzsignfoldersignerassociationRequest?
    public var objEzsignfoldersignerassociationCompound: EzsignfoldersignerassociationRequestCompound?

    public init(objEzsignfoldersignerassociation: EzsignfoldersignerassociationRequest? = nil, objEzsignfoldersignerassociationCompound: EzsignfoldersignerassociationRequestCompound? = nil) {
        self.objEzsignfoldersignerassociation = objEzsignfoldersignerassociation
        self.objEzsignfoldersignerassociationCompound = objEzsignfoldersignerassociationCompound
    }

}
