//
// EzsignfolderGetCommunicationListV1ResponseMPayloadAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EzsignfolderGetCommunicationListV1ResponseMPayloadAllOf: Codable, JSONEncodable, Hashable {

    public var aObjCommunication: [CustomCommunicationListElementResponse]

    public init(aObjCommunication: [CustomCommunicationListElementResponse]) {
        self.aObjCommunication = aObjCommunication
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aObjCommunication = "a_objCommunication"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aObjCommunication, forKey: .aObjCommunication)
    }
}

