//
// EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseMPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Payload for the /1/object/ezsignfoldersignerassociation/getInPersonLoginUrl API Request */
public struct EzsignfoldersignerassociationGetInPersonLoginUrlV1ResponseMPayload: Codable {

    /** The Url to login to the signing application.    Url will expire after 30 minutes.   */
    public var sLoginUrl: String

    public init(sLoginUrl: String) {
        self.sLoginUrl = sLoginUrl
    }

}
