//
// EzsigntemplatedocumentEditObjectV1ResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EzsigntemplatedocumentEditObjectV1ResponseAllOf: Codable, JSONEncodable, Hashable {

    public var aObjWarning: [CommonResponseWarning]?

    public init(aObjWarning: [CommonResponseWarning]? = nil) {
        self.aObjWarning = aObjWarning
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aObjWarning = "a_objWarning"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(aObjWarning, forKey: .aObjWarning)
    }
}

