//
// FieldEEzsignfolderStep.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The signature step of the Ezsignfolder. */
public enum FieldEEzsignfolderStep: String, Codable, CaseIterable {
    case unsent = "Unsent"
    case sent = "Sent"
    case partiallySigned = "PartiallySigned"
    case expired = "Expired"
    case signed = "Signed"
    case completed = "Completed"
    case archived = "Archived"
}
