//
// FieldECommunicationrecipientType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The type for the Communicationrecipient */
public enum FieldECommunicationrecipientType: String, Codable, CaseIterable {
    case to = "To"
    case cc = "Cc"
    case bcc = "Bcc"
}
