//
// ScimUserList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScimUserList: Codable, JSONEncodable, Hashable {

    public var totalResults: Int?
    public var itemsPerPage: Int?
    public var startIndex: Int?
    public var schemas: [String]?
    public var resources: [ScimUser]?

    public init(totalResults: Int? = nil, itemsPerPage: Int? = nil, startIndex: Int? = nil, schemas: [String]? = nil, resources: [ScimUser]? = nil) {
        self.totalResults = totalResults
        self.itemsPerPage = itemsPerPage
        self.startIndex = startIndex
        self.schemas = schemas
        self.resources = resources
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalResults
        case itemsPerPage
        case startIndex
        case schemas
        case resources = "Resources"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalResults, forKey: .totalResults)
        try container.encodeIfPresent(itemsPerPage, forKey: .itemsPerPage)
        try container.encodeIfPresent(startIndex, forKey: .startIndex)
        try container.encodeIfPresent(schemas, forKey: .schemas)
        try container.encodeIfPresent(resources, forKey: .resources)
    }
}

