//
// UNUSEDEzsignfolderEditObjectV1Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request for the /1/object/ezsignfolder/editObject API Request */
public struct UNUSEDEzsignfolderEditObjectV1Request: Codable, Hashable {

    public var objEzsignfolder: EzsignfolderRequest?

    public init(objEzsignfolder: EzsignfolderRequest? = nil) {
        self.objEzsignfolder = objEzsignfolder
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case objEzsignfolder
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(objEzsignfolder, forKey: .objEzsignfolder)
    }
}

