//
// UserEditObjectV1Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request for PUT /1/object/user/{pkiUserID} */
public struct UserEditObjectV1Request: Codable, JSONEncodable, Hashable {

    public var objUser: UserRequestCompound

    public init(objUser: UserRequestCompound) {
        self.objUser = objUser
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case objUser
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(objUser, forKey: .objUser)
    }
}

