//
// ObjectModulegroupAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ObjectModulegroupAPI {

    /**
     * enum for parameter eContext
     */
    public enum EContext_modulegroupGetAllV1: String, CaseIterable {
        case api = "Api"
        case user = "User"
    }

    /**
     Retrieve all Modulegroups
     
     - parameter eContext: (path) The context of the Modulegroup 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func modulegroupGetAllV1(eContext: EContext_modulegroupGetAllV1, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ModulegroupGetAllV1Response?, _ error: Error?) -> Void)) -> RequestTask {
        return modulegroupGetAllV1WithRequestBuilder(eContext: eContext).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Retrieve all Modulegroups
     - GET /1/object/modulegroup/getAll/{eContext}
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: Authorization
     - parameter eContext: (path) The context of the Modulegroup 
     - returns: RequestBuilder<ModulegroupGetAllV1Response> 
     */
    open class func modulegroupGetAllV1WithRequestBuilder(eContext: EContext_modulegroupGetAllV1) -> RequestBuilder<ModulegroupGetAllV1Response> {
        var localVariablePath = "/1/object/modulegroup/getAll/{eContext}"
        let eContextPreEscape = "\(eContext.rawValue)"
        let eContextPostEscape = eContextPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{eContext}", with: eContextPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ModulegroupGetAllV1Response>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
