//
// AgenttypeGetAutocompleteV2ResponseMPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for POST /2/object/agenttype/getAutocomplete */
public struct AgenttypeGetAutocompleteV2ResponseMPayload: Codable, JSONEncodable, Hashable {

    /** An array of Agenttype autocomplete element response. */
    public var aObjAgenttype: [AgenttypeAutocompleteElementResponse]

    public init(aObjAgenttype: [AgenttypeAutocompleteElementResponse]) {
        self.aObjAgenttype = aObjAgenttype
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aObjAgenttype = "a_objAgenttype"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aObjAgenttype, forKey: .aObjAgenttype)
    }
}

