//
// BillingentityinternalRequestCompound.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A Billingentityinternal Object and children */
public struct BillingentityinternalRequestCompound: Codable, JSONEncodable, Hashable {

    public static let pkiBillingentityinternalIDRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** The unique ID of the Billingentityinternal. */
    public var pkiBillingentityinternalID: Int?
    public var objBillingentityinternalDescription: MultilingualBillingentityinternalDescription
    public var aObjBillingentityinternalproduct: [BillingentityinternalproductRequestCompound]

    public init(pkiBillingentityinternalID: Int? = nil, objBillingentityinternalDescription: MultilingualBillingentityinternalDescription, aObjBillingentityinternalproduct: [BillingentityinternalproductRequestCompound]) {
        self.pkiBillingentityinternalID = pkiBillingentityinternalID
        self.objBillingentityinternalDescription = objBillingentityinternalDescription
        self.aObjBillingentityinternalproduct = aObjBillingentityinternalproduct
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pkiBillingentityinternalID
        case objBillingentityinternalDescription
        case aObjBillingentityinternalproduct = "a_objBillingentityinternalproduct"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pkiBillingentityinternalID, forKey: .pkiBillingentityinternalID)
        try container.encode(objBillingentityinternalDescription, forKey: .objBillingentityinternalDescription)
        try container.encode(aObjBillingentityinternalproduct, forKey: .aObjBillingentityinternalproduct)
    }
}

