//
// BuyercontractListElement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A Buyercontract List Element */
public struct BuyercontractListElement: Codable, JSONEncodable, Hashable {

    public static let pkiBuyercontractIDRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 65535, exclusiveMaximum: false, multipleOf: nil)
    public static let fkiInscriptiontypeIDRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 255, exclusiveMaximum: false, multipleOf: nil)
    public static let sInscriptiontypeNameXRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^.{0,30}$/")
    public static let dBuyercontractMinimumpriceRule = StringRule(minLength: 4, maxLength: 13, pattern: "/^-{0,1}[\\d]{1,9}?\\.[\\d]{2}$/")
    public static let dBuyercontractMaximumpriceRule = StringRule(minLength: 4, maxLength: 13, pattern: "/^-{0,1}[\\d]{1,9}?\\.[\\d]{2}$/")
    public static let dtBuyercontractDateRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/")
    public static let dtBuyercontractExpirationdateRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/")
    /** The unique ID of the Buyercontract */
    public var pkiBuyercontractID: Int
    /** The unique ID of the Inscriptiontype */
    public var fkiInscriptiontypeID: Int
    /** The name of the Inscriptiontype in the language of the requester */
    public var sInscriptiontypeNameX: String
    public var eBuyercontractStep: FieldEBuyercontractStep
    /** The minimumprice of the Buyercontract */
    public var dBuyercontractMinimumprice: String
    /** The maximumprice of the Buyercontract */
    public var dBuyercontractMaximumprice: String
    public var eBuyercontractType: FieldEBuyercontractType
    /** The date of the Buyercontract */
    public var dtBuyercontractDate: String
    /** The expirationdate of the Buyercontract */
    public var dtBuyercontractExpirationdate: String?
    /** Whether the buyercontract is active or not */
    public var bBuyercontractIsactive: Bool
    /** The brokers' name of the Buyercontract */
    public var sBuyercontractBrokers: String
    /** The buyers' name of the Buyercontract */
    public var sBuyercontractBuyers: String

    public init(pkiBuyercontractID: Int, fkiInscriptiontypeID: Int, sInscriptiontypeNameX: String, eBuyercontractStep: FieldEBuyercontractStep, dBuyercontractMinimumprice: String, dBuyercontractMaximumprice: String, eBuyercontractType: FieldEBuyercontractType, dtBuyercontractDate: String, dtBuyercontractExpirationdate: String? = nil, bBuyercontractIsactive: Bool, sBuyercontractBrokers: String, sBuyercontractBuyers: String) {
        self.pkiBuyercontractID = pkiBuyercontractID
        self.fkiInscriptiontypeID = fkiInscriptiontypeID
        self.sInscriptiontypeNameX = sInscriptiontypeNameX
        self.eBuyercontractStep = eBuyercontractStep
        self.dBuyercontractMinimumprice = dBuyercontractMinimumprice
        self.dBuyercontractMaximumprice = dBuyercontractMaximumprice
        self.eBuyercontractType = eBuyercontractType
        self.dtBuyercontractDate = dtBuyercontractDate
        self.dtBuyercontractExpirationdate = dtBuyercontractExpirationdate
        self.bBuyercontractIsactive = bBuyercontractIsactive
        self.sBuyercontractBrokers = sBuyercontractBrokers
        self.sBuyercontractBuyers = sBuyercontractBuyers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pkiBuyercontractID
        case fkiInscriptiontypeID
        case sInscriptiontypeNameX
        case eBuyercontractStep
        case dBuyercontractMinimumprice
        case dBuyercontractMaximumprice
        case eBuyercontractType
        case dtBuyercontractDate
        case dtBuyercontractExpirationdate
        case bBuyercontractIsactive
        case sBuyercontractBrokers
        case sBuyercontractBuyers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pkiBuyercontractID, forKey: .pkiBuyercontractID)
        try container.encode(fkiInscriptiontypeID, forKey: .fkiInscriptiontypeID)
        try container.encode(sInscriptiontypeNameX, forKey: .sInscriptiontypeNameX)
        try container.encode(eBuyercontractStep, forKey: .eBuyercontractStep)
        try container.encode(dBuyercontractMinimumprice, forKey: .dBuyercontractMinimumprice)
        try container.encode(dBuyercontractMaximumprice, forKey: .dBuyercontractMaximumprice)
        try container.encode(eBuyercontractType, forKey: .eBuyercontractType)
        try container.encode(dtBuyercontractDate, forKey: .dtBuyercontractDate)
        try container.encodeIfPresent(dtBuyercontractExpirationdate, forKey: .dtBuyercontractExpirationdate)
        try container.encode(bBuyercontractIsactive, forKey: .bBuyercontractIsactive)
        try container.encode(sBuyercontractBrokers, forKey: .sBuyercontractBrokers)
        try container.encode(sBuyercontractBuyers, forKey: .sBuyercontractBuyers)
    }
}

