//
// CommonResponseWarning.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Generic Warning Message */
public struct CommonResponseWarning: Codable, JSONEncodable, Hashable {

    /** More detail about the warning */
    public var sWarningMessage: String
    /** The warning code. See documentation for valid values */
    public var eWarningCode: String

    public init(sWarningMessage: String, eWarningCode: String) {
        self.sWarningMessage = sWarningMessage
        self.eWarningCode = eWarningCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sWarningMessage
        case eWarningCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sWarningMessage, forKey: .sWarningMessage)
        try container.encode(eWarningCode, forKey: .eWarningCode)
    }
}

