//
// CustomEzsigndocumentGetEzsignannotationsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An Ezsigndocument Object in the context of a getEzsignannotations path */
public struct CustomEzsigndocumentGetEzsignannotationsResponse: Codable, JSONEncodable, Hashable {

    public static let pkiEzsigndocumentIDRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** The unique ID of the Ezsigndocument */
    public var pkiEzsigndocumentID: Int
    /** The name of the document that will be presented to Ezsignfoldersignerassociations */
    public var sEzsigndocumentName: String
    public var aObjEzsignannotation: [EzsignannotationResponseCompound]

    public init(pkiEzsigndocumentID: Int, sEzsigndocumentName: String, aObjEzsignannotation: [EzsignannotationResponseCompound]) {
        self.pkiEzsigndocumentID = pkiEzsigndocumentID
        self.sEzsigndocumentName = sEzsigndocumentName
        self.aObjEzsignannotation = aObjEzsignannotation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pkiEzsigndocumentID
        case sEzsigndocumentName
        case aObjEzsignannotation = "a_objEzsignannotation"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pkiEzsigndocumentID, forKey: .pkiEzsigndocumentID)
        try container.encode(sEzsigndocumentName, forKey: .sEzsigndocumentName)
        try container.encode(aObjEzsignannotation, forKey: .aObjEzsignannotation)
    }
}

