//
// DiscussionmessageCreateObjectV1Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request for POST /1/object/discussionmessage */
public struct DiscussionmessageCreateObjectV1Request: Codable, JSONEncodable, Hashable {

    public static let aObjDiscussionmessageRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var aObjDiscussionmessage: [DiscussionmessageRequestCompound]

    public init(aObjDiscussionmessage: [DiscussionmessageRequestCompound]) {
        self.aObjDiscussionmessage = aObjDiscussionmessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aObjDiscussionmessage = "a_objDiscussionmessage"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aObjDiscussionmessage, forKey: .aObjDiscussionmessage)
    }
}

