//
// EzmaxpartnerGetCustomDeveloppersV1ResponseMPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for GET /1/object/ezmaxpartner/getCustomDeveloppers */
public struct EzmaxpartnerGetCustomDeveloppersV1ResponseMPayload: Codable, JSONEncodable, Hashable {

    public var aObjEzmaxpartner: [CustomEzmaxpartnerListElement]

    public init(aObjEzmaxpartner: [CustomEzmaxpartnerListElement]) {
        self.aObjEzmaxpartner = aObjEzmaxpartner
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aObjEzmaxpartner = "a_objEzmaxpartner"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aObjEzmaxpartner, forKey: .aObjEzmaxpartner)
    }
}

