//
// EzsignsignergroupGetObjectV2ResponseMPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for GET /2/object/ezsignsignergroup/{pkiEzsignsignergroupID} */
public struct EzsignsignergroupGetObjectV2ResponseMPayload: Codable, JSONEncodable, Hashable {

    public var objEzsignsignergroup: EzsignsignergroupResponseCompound

    public init(objEzsignsignergroup: EzsignsignergroupResponseCompound) {
        self.objEzsignsignergroup = objEzsignsignergroup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case objEzsignsignergroup
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(objEzsignsignergroup, forKey: .objEzsignsignergroup)
    }
}

