//
// EzsigntemplatepackageGetObjectV3ResponseMPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for GET /3/object/ezsigntemplatepackage/{pkiEzsigntemplatepackageID} */
public struct EzsigntemplatepackageGetObjectV3ResponseMPayload: Codable, JSONEncodable, Hashable {

    public var objEzsigntemplatepackage: EzsigntemplatepackageResponseCompoundV3

    public init(objEzsigntemplatepackage: EzsigntemplatepackageResponseCompoundV3) {
        self.objEzsigntemplatepackage = objEzsigntemplatepackage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case objEzsigntemplatepackage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(objEzsigntemplatepackage, forKey: .objEzsigntemplatepackage)
    }
}

