//
// EzsigntemplateglobalannotationResponseCompound.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A Ezsigntemplateglobalannotation Object */
public struct EzsigntemplateglobalannotationResponseCompound: Codable, JSONEncodable, Hashable {

    public static let pkiEzsigntemplateglobalannotationIDRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 16777215, exclusiveMaximum: false, multipleOf: nil)
    public static let fkiEzsigntemplateglobaldocumentpageIDRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 16777215, exclusiveMaximum: false, multipleOf: nil)
    public static let fkiTextstylestaticIDRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let iEzsigntemplateglobalannotationXRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 65535, exclusiveMaximum: false, multipleOf: nil)
    public static let iEzsigntemplateglobalannotationYRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 65535, exclusiveMaximum: false, multipleOf: nil)
    public static let iEzsigntemplateglobalannotationWidthRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 65535, exclusiveMaximum: false, multipleOf: nil)
    public static let iEzsigntemplateglobalannotationHeightRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 65535, exclusiveMaximum: false, multipleOf: nil)
    public static let sEzsigntemplateglobalannotationDescriptionRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^.{0,80}$/")
    public static let sEzsigntemplateglobalannotationDefaulttextRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^.{0,65535}$/")
    public static let sEzsigntemplateglobalannotationDropdownvaluesRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^.{0,65535}$/")
    /** The unique ID of the Ezsigntemplateglobalannotation */
    public var pkiEzsigntemplateglobalannotationID: Int
    /** The unique ID of the Ezsigntemplateglobaldocumentpage */
    public var fkiEzsigntemplateglobaldocumentpageID: Int
    /** The unique ID of the Textstylestatic */
    public var fkiTextstylestaticID: Int
    public var eEzsigntemplateglobalannotationHorizontalalignment: FieldEEzsigntemplateglobalannotationHorizontalalignment
    public var eEzsigntemplateglobalannotationVerticalalignment: FieldEEzsigntemplateglobalannotationVerticalalignment
    public var eEzsigntemplateglobalannotationType: FieldEEzsigntemplateglobalannotationType
    /** The x of the Ezsigntemplateglobalannotation */
    public var iEzsigntemplateglobalannotationX: Int
    /** The y of the Ezsigntemplateglobalannotation */
    public var iEzsigntemplateglobalannotationY: Int
    /** The width of the Ezsigntemplateglobalannotation */
    public var iEzsigntemplateglobalannotationWidth: Int
    /** The height of the Ezsigntemplateglobalannotation */
    public var iEzsigntemplateglobalannotationHeight: Int
    /** The description of the Ezsigntemplateglobalannotation */
    public var sEzsigntemplateglobalannotationDescription: String
    /** The defaulttext of the Ezsigntemplateglobalannotation */
    public var sEzsigntemplateglobalannotationDefaulttext: String
    /** The dropdownvalues of the Ezsigntemplateglobalannotation */
    public var sEzsigntemplateglobalannotationDropdownvalues: String

    public init(pkiEzsigntemplateglobalannotationID: Int, fkiEzsigntemplateglobaldocumentpageID: Int, fkiTextstylestaticID: Int, eEzsigntemplateglobalannotationHorizontalalignment: FieldEEzsigntemplateglobalannotationHorizontalalignment, eEzsigntemplateglobalannotationVerticalalignment: FieldEEzsigntemplateglobalannotationVerticalalignment, eEzsigntemplateglobalannotationType: FieldEEzsigntemplateglobalannotationType, iEzsigntemplateglobalannotationX: Int, iEzsigntemplateglobalannotationY: Int, iEzsigntemplateglobalannotationWidth: Int, iEzsigntemplateglobalannotationHeight: Int, sEzsigntemplateglobalannotationDescription: String, sEzsigntemplateglobalannotationDefaulttext: String, sEzsigntemplateglobalannotationDropdownvalues: String) {
        self.pkiEzsigntemplateglobalannotationID = pkiEzsigntemplateglobalannotationID
        self.fkiEzsigntemplateglobaldocumentpageID = fkiEzsigntemplateglobaldocumentpageID
        self.fkiTextstylestaticID = fkiTextstylestaticID
        self.eEzsigntemplateglobalannotationHorizontalalignment = eEzsigntemplateglobalannotationHorizontalalignment
        self.eEzsigntemplateglobalannotationVerticalalignment = eEzsigntemplateglobalannotationVerticalalignment
        self.eEzsigntemplateglobalannotationType = eEzsigntemplateglobalannotationType
        self.iEzsigntemplateglobalannotationX = iEzsigntemplateglobalannotationX
        self.iEzsigntemplateglobalannotationY = iEzsigntemplateglobalannotationY
        self.iEzsigntemplateglobalannotationWidth = iEzsigntemplateglobalannotationWidth
        self.iEzsigntemplateglobalannotationHeight = iEzsigntemplateglobalannotationHeight
        self.sEzsigntemplateglobalannotationDescription = sEzsigntemplateglobalannotationDescription
        self.sEzsigntemplateglobalannotationDefaulttext = sEzsigntemplateglobalannotationDefaulttext
        self.sEzsigntemplateglobalannotationDropdownvalues = sEzsigntemplateglobalannotationDropdownvalues
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pkiEzsigntemplateglobalannotationID
        case fkiEzsigntemplateglobaldocumentpageID
        case fkiTextstylestaticID
        case eEzsigntemplateglobalannotationHorizontalalignment
        case eEzsigntemplateglobalannotationVerticalalignment
        case eEzsigntemplateglobalannotationType
        case iEzsigntemplateglobalannotationX
        case iEzsigntemplateglobalannotationY
        case iEzsigntemplateglobalannotationWidth
        case iEzsigntemplateglobalannotationHeight
        case sEzsigntemplateglobalannotationDescription
        case sEzsigntemplateglobalannotationDefaulttext
        case sEzsigntemplateglobalannotationDropdownvalues
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pkiEzsigntemplateglobalannotationID, forKey: .pkiEzsigntemplateglobalannotationID)
        try container.encode(fkiEzsigntemplateglobaldocumentpageID, forKey: .fkiEzsigntemplateglobaldocumentpageID)
        try container.encode(fkiTextstylestaticID, forKey: .fkiTextstylestaticID)
        try container.encode(eEzsigntemplateglobalannotationHorizontalalignment, forKey: .eEzsigntemplateglobalannotationHorizontalalignment)
        try container.encode(eEzsigntemplateglobalannotationVerticalalignment, forKey: .eEzsigntemplateglobalannotationVerticalalignment)
        try container.encode(eEzsigntemplateglobalannotationType, forKey: .eEzsigntemplateglobalannotationType)
        try container.encode(iEzsigntemplateglobalannotationX, forKey: .iEzsigntemplateglobalannotationX)
        try container.encode(iEzsigntemplateglobalannotationY, forKey: .iEzsigntemplateglobalannotationY)
        try container.encode(iEzsigntemplateglobalannotationWidth, forKey: .iEzsigntemplateglobalannotationWidth)
        try container.encode(iEzsigntemplateglobalannotationHeight, forKey: .iEzsigntemplateglobalannotationHeight)
        try container.encode(sEzsigntemplateglobalannotationDescription, forKey: .sEzsigntemplateglobalannotationDescription)
        try container.encode(sEzsigntemplateglobalannotationDefaulttext, forKey: .sEzsigntemplateglobalannotationDefaulttext)
        try container.encode(sEzsigntemplateglobalannotationDropdownvalues, forKey: .sEzsigntemplateglobalannotationDropdownvalues)
    }
}

