//
// EzsigntemplateCreateObjectV3ResponseMPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for POST /3/object/ezsigntemplate */
public struct EzsigntemplateCreateObjectV3ResponseMPayload: Codable, JSONEncodable, Hashable {

    static let aPkiEzsigntemplateIDRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    /** An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request. */
    public var aPkiEzsigntemplateID: [Int]

    public init(aPkiEzsigntemplateID: [Int]) {
        self.aPkiEzsigntemplateID = aPkiEzsigntemplateID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aPkiEzsigntemplateID = "a_pkiEzsigntemplateID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aPkiEzsigntemplateID, forKey: .aPkiEzsigntemplateID)
    }
}

