//
// EzsigntemplatesignaturepaymentdetailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An Ezsigntemplatesignaturepaymentdetail Object */
public struct EzsigntemplatesignaturepaymentdetailResponse: Codable, JSONEncodable, Hashable {

    public static let pkiEzsigntemplatesignaturepaymentdetailIDRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 65535, exclusiveMaximum: false, multipleOf: nil)
    public static let fkiGlaccountcontainerIDRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let dEzsigntemplatesignaturepaymentdetailAmountRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[\\d]{1,3}?\\.[\\d]{2}$/")
    /** The unique ID of the Ezsignsignaturepaymentdetail */
    public var pkiEzsigntemplatesignaturepaymentdetailID: Int
    /** The unique ID of the Glaccountcontainer */
    public var fkiGlaccountcontainerID: Int?
    /** A description for the Ezsignsignaturepaymentdetail. */
    public var tEzsigntemplatesignaturepaymentdetailDescription: String
    /** The amount of the for the Ezsignsignaturepaymentdetail */
    public var dEzsigntemplatesignaturepaymentdetailAmount: String
    public var eEzsigntemplatesignaturepaymentdetailTaxable: FieldEEzsigntemplatesignaturepaymentdetailTaxable

    public init(pkiEzsigntemplatesignaturepaymentdetailID: Int, fkiGlaccountcontainerID: Int? = nil, tEzsigntemplatesignaturepaymentdetailDescription: String, dEzsigntemplatesignaturepaymentdetailAmount: String, eEzsigntemplatesignaturepaymentdetailTaxable: FieldEEzsigntemplatesignaturepaymentdetailTaxable) {
        self.pkiEzsigntemplatesignaturepaymentdetailID = pkiEzsigntemplatesignaturepaymentdetailID
        self.fkiGlaccountcontainerID = fkiGlaccountcontainerID
        self.tEzsigntemplatesignaturepaymentdetailDescription = tEzsigntemplatesignaturepaymentdetailDescription
        self.dEzsigntemplatesignaturepaymentdetailAmount = dEzsigntemplatesignaturepaymentdetailAmount
        self.eEzsigntemplatesignaturepaymentdetailTaxable = eEzsigntemplatesignaturepaymentdetailTaxable
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pkiEzsigntemplatesignaturepaymentdetailID
        case fkiGlaccountcontainerID
        case tEzsigntemplatesignaturepaymentdetailDescription
        case dEzsigntemplatesignaturepaymentdetailAmount
        case eEzsigntemplatesignaturepaymentdetailTaxable
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pkiEzsigntemplatesignaturepaymentdetailID, forKey: .pkiEzsigntemplatesignaturepaymentdetailID)
        try container.encodeIfPresent(fkiGlaccountcontainerID, forKey: .fkiGlaccountcontainerID)
        try container.encode(tEzsigntemplatesignaturepaymentdetailDescription, forKey: .tEzsigntemplatesignaturepaymentdetailDescription)
        try container.encode(dEzsigntemplatesignaturepaymentdetailAmount, forKey: .dEzsigntemplatesignaturepaymentdetailAmount)
        try container.encode(eEzsigntemplatesignaturepaymentdetailTaxable, forKey: .eEzsigntemplatesignaturepaymentdetailTaxable)
    }
}

