//
// EzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseMPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for PUT /1/object/ezsigntemplatedocument/{pkiEzsigntemplatedocumentID}/editEzsigntemplatesignatures */
public struct EzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseMPayload: Codable, JSONEncodable, Hashable {

    public var aPkiEzsigntemplatesignatureID: [Int]

    public init(aPkiEzsigntemplatesignatureID: [Int]) {
        self.aPkiEzsigntemplatesignatureID = aPkiEzsigntemplatesignatureID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aPkiEzsigntemplatesignatureID = "a_pkiEzsigntemplatesignatureID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aPkiEzsigntemplatesignatureID, forKey: .aPkiEzsigntemplatesignatureID)
    }
}

