//
// FieldESystemconfigurationLanguage1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The type of the french for the client */
public enum FieldESystemconfigurationLanguage1: String, Codable, CaseIterable {
    case frQc = "fr_QC"
}
