//
// FieldEEzsignsignatureSignaturepad.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The type of signature pad required. */
public enum FieldEEzsignsignatureSignaturepad: String, Codable, CaseIterable {
    case topaz = "Topaz"
}
