//
// FieldEEzsignformfieldgroupSignerrequirement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The Signer requirement of the Ezsignformfieldgroup. **All** means anyone can fill it, **One** means a specific person must fill it. */
public enum FieldEEzsignformfieldgroupSignerrequirement: String, Codable, CaseIterable {
    case all = "All"
    case one = "One"
}
