//
// FieldEEzsigntemplatedocumentpagerecognitionOperator.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The operator of the Ezsigntemplatedocumentpagerecognition */
public enum FieldEEzsigntemplatedocumentpagerecognitionOperator: String, Codable, CaseIterable {
    case eq = "eq"
    case _in = "in"
    case similar = "similar"
}
