//
// FieldEEzsignfoldertypeSigneraccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Indicates which documents the user has access to. */
public enum FieldEEzsignfoldertypeSigneraccess: String, Codable, CaseIterable {
    case no = "No"
    case signerDocuments = "SignerDocuments"
    case allDocuments = "AllDocuments"
}
