//
// FieldEEzsigntemplatesignatureAttachmentnamesource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The source of the name of the attachment added to the Ezsigntemplatesignature */
public enum FieldEEzsigntemplatesignatureAttachmentnamesource: String, Codable, CaseIterable {
    case description = "Description"
    case customer = "Customer"
    case descriptionCustomer = "DescriptionCustomer"
}
