//
// FieldESystemconfigurationEzsignofficeplan.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Plan choose of this company for eZsign if Ezsign is paid by the company */
public enum FieldESystemconfigurationEzsignofficeplan: String, Codable, CaseIterable {
    case standard = "Standard"
    case pro = "Pro"
}
