//
// FieldEEzsignsignatureConsultationtrigger.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Indicates when the “consultation” type signature must be signed.  1. **Automatic** When the document is displayed . 2. **Manual** The user must indicate that he has viewed the document. 3. **Optional** The user can view the document, but they are not required to do so. Same as **Automatic** when user view the document. */
public enum FieldEEzsignsignatureConsultationtrigger: String, Codable, CaseIterable {
    case automatic = "Automatic"
    case manual = "Manual"
    case _optional = "Optional"
}
