//
// FieldEInscriptionnotauthenticatedRemunerationtype.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The type of remuneration of the Inscriptionnotauthenticated */
public enum FieldEInscriptionnotauthenticatedRemunerationtype: String, Codable, CaseIterable {
    case percentage = "Percentage"
    case percentageTaxesIncluded = "PercentageTaxesIncluded"
    case dollars = "Dollars"
    case dollarsTaxesIncluded = "DollarsTaxesIncluded"
}
