//
// FieldESignaturePreference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The Preference of the Signature */
public enum FieldESignaturePreference: String, Codable, CaseIterable {
    case text = "Text"
    case handwritten = "Handwritten"
}
