//
// FieldEInscriptionRemunerationtotaltype.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The remunerationtotaltype of the Inscription */
public enum FieldEInscriptionRemunerationtotaltype: String, Codable, CaseIterable {
    case percentage = "Percentage"
    case dollars = "Dollars"
}
