//
// FieldEEzsignfoldertypeSignaturedatedisplay.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** How we display the date in signatures */
public enum FieldEEzsignfoldertypeSignaturedatedisplay: String, Codable, CaseIterable {
    case _default = "Default"
    case hidden = "Hidden"
    case custom = "Custom"
}
