//
// FieldEEzsigntemplateglobalModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The Module for the Ezsigntemplateglobal */
public enum FieldEEzsigntemplateglobalModule: String, Codable, CaseIterable {
    case all = "All"
    case inscription = "Inscription"
}
