//
// FieldEEzsigntemplatesignaturePositioning.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** How the positioning of the Ezsigntemplatesignature will be done */
public enum FieldEEzsigntemplatesignaturePositioning: String, Codable, CaseIterable {
    case perCoordinates = "PerCoordinates"
    case perPositioningPattern = "PerPositioningPattern"
}
