//
// FieldEEzsigntemplateRecognition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Indicates whether we use the name or the content to recognize the templates to be automatically applied to documents */
public enum FieldEEzsigntemplateRecognition: String, Codable, CaseIterable {
    case no = "No"
    case filename = "Filename"
    case content = "Content"
}
