//
// FieldEEzsigntemplateglobalannotationHorizontalalignment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The horizontalalignment of the Ezsigntemplateglobalannotation */
public enum FieldEEzsigntemplateglobalannotationHorizontalalignment: String, Codable, CaseIterable {
    case center = "Center"
    case _left = "Left"
    case _right = "Right"
}
