//
// FieldEEzsignfolderSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The source of the Ezsignfolder. */
public enum FieldEEzsignfolderSource: String, Codable, CaseIterable {
    case normal = "Normal"
    case ezsignbulksend = "Ezsignbulksend"
    case ezsigntemplatepublic = "Ezsigntemplatepublic"
}
