//
// GlaccountGetAutocompleteV2ResponseMPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for POST /2/object/glaccount/getAutocomplete */
public struct GlaccountGetAutocompleteV2ResponseMPayload: Codable, JSONEncodable, Hashable {

    /** An array of Glaccount autocomplete element response. */
    public var aObjGlaccount: [GlaccountAutocompleteElementResponse]

    public init(aObjGlaccount: [GlaccountAutocompleteElementResponse]) {
        self.aObjGlaccount = aObjGlaccount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aObjGlaccount = "a_objGlaccount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aObjGlaccount, forKey: .aObjGlaccount)
    }
}

