//
// GlobalEzmaxclientVersionV1Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response for GET /1/ezmaxclient/{pksEzmaxclientOs}/version */
public struct GlobalEzmaxclientVersionV1Response: Codable, JSONEncodable, Hashable {

    /** The version on the store */
    public var sEzmaxclientVersion: String

    public init(sEzmaxclientVersion: String) {
        self.sEzmaxclientVersion = sEzmaxclientVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sEzmaxclientVersion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sEzmaxclientVersion, forKey: .sEzmaxclientVersion)
    }
}

