//
// InvoiceGetAttachmentsV1ResponseMPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response for GET /1/object/invoice/{pkiInvoiceID}/getAttachments */
public struct InvoiceGetAttachmentsV1ResponseMPayload: Codable, JSONEncodable, Hashable {

    public var aObjAttachmentdocumenttype: [CustomAttachmentdocumenttypeResponse]

    public init(aObjAttachmentdocumenttype: [CustomAttachmentdocumenttypeResponse]) {
        self.aObjAttachmentdocumenttype = aObjAttachmentdocumenttype
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aObjAttachmentdocumenttype = "a_objAttachmentdocumenttype"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aObjAttachmentdocumenttype, forKey: .aObjAttachmentdocumenttype)
    }
}

