//
// LeadsourceAutocompleteElementResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A Leadsource AutocompleteElement Response */
public struct LeadsourceAutocompleteElementResponse: Codable, JSONEncodable, Hashable {

    public static let pkiLeadsourceIDRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 255, exclusiveMaximum: false, multipleOf: nil)
    public static let sLeadsourceNameXRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^.{0,25}$/")
    /** The unique ID of the Leadsource */
    public var pkiLeadsourceID: Int
    /** The name of the Leadsource in the language of the requester */
    public var sLeadsourceNameX: String
    /** Whether the Leadsource is active or not */
    public var bLeadsourceIsactive: Bool

    public init(pkiLeadsourceID: Int, sLeadsourceNameX: String, bLeadsourceIsactive: Bool) {
        self.pkiLeadsourceID = pkiLeadsourceID
        self.sLeadsourceNameX = sLeadsourceNameX
        self.bLeadsourceIsactive = bLeadsourceIsactive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pkiLeadsourceID
        case sLeadsourceNameX
        case bLeadsourceIsactive
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pkiLeadsourceID, forKey: .pkiLeadsourceID)
        try container.encode(sLeadsourceNameX, forKey: .sLeadsourceNameX)
        try container.encode(bLeadsourceIsactive, forKey: .bLeadsourceIsactive)
    }
}

