//
// NotaryBatchDownloadV1Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request for POST /1/object/notary/{pkiNotaryID}/batchDownload */
public struct NotaryBatchDownloadV1Request: Codable, JSONEncodable, Hashable {

    public static let aPkiAttachmentIDRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var aPkiAttachmentID: [Int]

    public init(aPkiAttachmentID: [Int]) {
        self.aPkiAttachmentID = aPkiAttachmentID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aPkiAttachmentID = "a_pkiAttachmentID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aPkiAttachmentID, forKey: .aPkiAttachmentID)
    }
}

