//
// OtherincomeListElement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A Otherincome List Element */
public struct OtherincomeListElement: Codable, JSONEncodable, Hashable {

    public static let pkiOtherincomeIDRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 65535, exclusiveMaximum: false, multipleOf: nil)
    public static let fkiOtherincometypeIDRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 255, exclusiveMaximum: false, multipleOf: nil)
    public static let sOtherincometypeDescriptionXRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^.{0,255}$/")
    public static let sOtherincomeDescriptionRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(\\n|.){0,75}$/")
    public static let dOtherincomeRemunerationsubtotalRule = StringRule(minLength: 4, maxLength: 13, pattern: "/^-{0,1}[\\d]{1,9}?\\.[\\d]{2}$/")
    public static let dOtherincomeRemunerationtaxesRule = StringRule(minLength: 4, maxLength: 13, pattern: "/^-{0,1}[\\d]{1,9}?\\.[\\d]{2}$/")
    public static let dOtherincomeRemunerationtotalRule = StringRule(minLength: 4, maxLength: 13, pattern: "/^-{0,1}[\\d]{1,9}?\\.[\\d]{2}$/")
    public static let dtOtherincomePaidRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/")
    /** The unique ID of the Otherincome */
    public var pkiOtherincomeID: Int
    /** The unique ID of the Otherincometype */
    public var fkiOtherincometypeID: Int
    /** The description of the Otherincometype in the language of the requester */
    public var sOtherincometypeDescriptionX: String
    /** The description of the Otherincome */
    public var sOtherincomeDescription: String
    public var eOtherincomeRemunerationtype: FieldEOtherincomeRemunerationtype
    /** The remuneration subtotal of the Otherincome */
    public var dOtherincomeRemunerationsubtotal: String
    /** The remuneration total taxes of the Otherincome */
    public var dOtherincomeRemunerationtaxes: String?
    /** The remuneration total of the Otherincome */
    public var dOtherincomeRemunerationtotal: String?
    /** The paid of the Otherincome */
    public var dtOtherincomePaid: String
    /** Whether the otherincome is active or not */
    public var bOtherincomeIsactive: Bool

    public init(pkiOtherincomeID: Int, fkiOtherincometypeID: Int, sOtherincometypeDescriptionX: String, sOtherincomeDescription: String, eOtherincomeRemunerationtype: FieldEOtherincomeRemunerationtype, dOtherincomeRemunerationsubtotal: String, dOtherincomeRemunerationtaxes: String? = nil, dOtherincomeRemunerationtotal: String? = nil, dtOtherincomePaid: String, bOtherincomeIsactive: Bool) {
        self.pkiOtherincomeID = pkiOtherincomeID
        self.fkiOtherincometypeID = fkiOtherincometypeID
        self.sOtherincometypeDescriptionX = sOtherincometypeDescriptionX
        self.sOtherincomeDescription = sOtherincomeDescription
        self.eOtherincomeRemunerationtype = eOtherincomeRemunerationtype
        self.dOtherincomeRemunerationsubtotal = dOtherincomeRemunerationsubtotal
        self.dOtherincomeRemunerationtaxes = dOtherincomeRemunerationtaxes
        self.dOtherincomeRemunerationtotal = dOtherincomeRemunerationtotal
        self.dtOtherincomePaid = dtOtherincomePaid
        self.bOtherincomeIsactive = bOtherincomeIsactive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pkiOtherincomeID
        case fkiOtherincometypeID
        case sOtherincometypeDescriptionX
        case sOtherincomeDescription
        case eOtherincomeRemunerationtype
        case dOtherincomeRemunerationsubtotal
        case dOtherincomeRemunerationtaxes
        case dOtherincomeRemunerationtotal
        case dtOtherincomePaid
        case bOtherincomeIsactive
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pkiOtherincomeID, forKey: .pkiOtherincomeID)
        try container.encode(fkiOtherincometypeID, forKey: .fkiOtherincometypeID)
        try container.encode(sOtherincometypeDescriptionX, forKey: .sOtherincometypeDescriptionX)
        try container.encode(sOtherincomeDescription, forKey: .sOtherincomeDescription)
        try container.encode(eOtherincomeRemunerationtype, forKey: .eOtherincomeRemunerationtype)
        try container.encode(dOtherincomeRemunerationsubtotal, forKey: .dOtherincomeRemunerationsubtotal)
        try container.encodeIfPresent(dOtherincomeRemunerationtaxes, forKey: .dOtherincomeRemunerationtaxes)
        try container.encodeIfPresent(dOtherincomeRemunerationtotal, forKey: .dOtherincomeRemunerationtotal)
        try container.encode(dtOtherincomePaid, forKey: .dtOtherincomePaid)
        try container.encode(bOtherincomeIsactive, forKey: .bOtherincomeIsactive)
    }
}

