//
// PaymentgatewayGetAutocompleteV2ResponseMPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for POST /2/object/paymentgateway/getAutocomplete */
public struct PaymentgatewayGetAutocompleteV2ResponseMPayload: Codable, JSONEncodable, Hashable {

    /** An array of Paymentgateway autocomplete element response. */
    public var aObjPaymentgateway: [PaymentgatewayAutocompleteElementResponse]

    public init(aObjPaymentgateway: [PaymentgatewayAutocompleteElementResponse]) {
        self.aObjPaymentgateway = aObjPaymentgateway
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aObjPaymentgateway = "a_objPaymentgateway"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aObjPaymentgateway, forKey: .aObjPaymentgateway)
    }
}

