//
// RejectedoffertopurchaseImportIntoEDMV1Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request for POST /1/object/rejectedoffertopurchase/{pkiRejectedoffertopurchaseID}/importIntoEDM */
public struct RejectedoffertopurchaseImportIntoEDMV1Request: Codable, JSONEncodable, Hashable {

    public var aObjAttachment: [CustomAttachmentImportIntoEDMRequest]

    public init(aObjAttachment: [CustomAttachmentImportIntoEDMRequest]) {
        self.aObjAttachment = aObjAttachment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aObjAttachment = "a_objAttachment"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aObjAttachment, forKey: .aObjAttachment)
    }
}

