//
// ScimServiceProviderConfigBulk.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A complex type that specifies bulk configuration options. */
public struct ScimServiceProviderConfigBulk: Codable, JSONEncodable, Hashable {

    /** A Boolean value specifying whether or not the operation is supported. */
    public var supported: Bool
    /** An integer value specifying the maximum number of operations. */
    public var maxOperations: Int
    /** An integer value specifying the maximum payload size in bytes. */
    public var maxPayloadSize: Int

    public init(supported: Bool, maxOperations: Int, maxPayloadSize: Int) {
        self.supported = supported
        self.maxOperations = maxOperations
        self.maxPayloadSize = maxPayloadSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case supported
        case maxOperations
        case maxPayloadSize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(supported, forKey: .supported)
        try container.encode(maxOperations, forKey: .maxOperations)
        try container.encode(maxPayloadSize, forKey: .maxPayloadSize)
    }
}

