//
// TaxassignmentGetAutocompleteV2ResponseMPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for POST /2/object/taxassignment/getAutocomplete */
public struct TaxassignmentGetAutocompleteV2ResponseMPayload: Codable, JSONEncodable, Hashable {

    /** An array of Taxassignment autocomplete element response. */
    public var aObjTaxassignment: [TaxassignmentAutocompleteElementResponse]

    public init(aObjTaxassignment: [TaxassignmentAutocompleteElementResponse]) {
        self.aObjTaxassignment = aObjTaxassignment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aObjTaxassignment = "a_objTaxassignment"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aObjTaxassignment, forKey: .aObjTaxassignment)
    }
}

