//
// WebhookRealestateInscriptionnotauthenticatedCreated.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This is a webhook for a RealestateInscriptionnotauthenticatedCreated event */
public struct WebhookRealestateInscriptionnotauthenticatedCreated: Codable, JSONEncodable, Hashable {

    public var objWebhook: CustomWebhookResponse
    /** An array containing details of previous attempts that were made to deliver the message. The array is empty if it's the first attempt. */
    public var aObjAttempt: [AttemptResponseCompound]
    public var objInscriptionnotauthenticated: InscriptionnotauthenticatedResponse

    public init(objWebhook: CustomWebhookResponse, aObjAttempt: [AttemptResponseCompound], objInscriptionnotauthenticated: InscriptionnotauthenticatedResponse) {
        self.objWebhook = objWebhook
        self.aObjAttempt = aObjAttempt
        self.objInscriptionnotauthenticated = objInscriptionnotauthenticated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case objWebhook
        case aObjAttempt = "a_objAttempt"
        case objInscriptionnotauthenticated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(objWebhook, forKey: .objWebhook)
        try container.encode(aObjAttempt, forKey: .aObjAttempt)
        try container.encode(objInscriptionnotauthenticated, forKey: .objInscriptionnotauthenticated)
    }
}

